### ISSUE TITLE
Segment-Tune doesn't support Segment 3.2.*

### ISSUE THREAD

**Issue by ldiqual** [TuneOSS/segment-integration-ios#3]
This line https://github.com/MobileAppTracking/segment-integration-ios/blob/master/Segment-Tune.podspec#L39

```
s.dependency 'Analytics', '~> 3.0.0'
```

should probably be

```
s.dependency 'Analytics', '~> 3.0'
```

Related: https://github.com/segment-integrations/analytics-ios-integration-mixpanel/issues/14

**Comment by john-gu** [comment]
Hi, this is fixed with 1.0.2:
https://github.com/MobileAppTracking/segment-integration-ios/releases/tag/1.0.2

It's now available on CocoaPods:
http://cocoapods.org/pods/Segment-Tune
