### ISSUE TITLE
pod install: "target has transitive dependencies that include static binaries"

### ISSUE THREAD

**Issue by ldiqual** [TuneOSS/segment-integration-ios#4]
When trying to add 

```
pod 'Segment-Tune', '1.0.2'
```

and running `pod install`, I get the following error:

```
[!] The '<mytarget>' target has transitive dependencies that include static binaries: (/path/to/pods/Tune/Tune.framework)
```

which seems to be due to this: https://github.com/CocoaPods/CocoaPods/issues/2926

I was able to workaround the error by adding [this](https://github.com/CocoaPods/CocoaPods/issues/2926#issuecomment-136766631) to my Podfile:

```
pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    def installer.verify_no_static_framework_transitive_dependencies; end
end
```

However after the workaround I get this new error when compiling:

```
#import <Tune/Tune.h> // /path/to/pods/Segment-Tune/Segment-Tune/Classes/SEGTuneIntegration.h:3:9: 'Tune/Tune.h' file not found
```

Any workaround?

**Comment by john-gu** [comment]
Hi @ldiqual, what CocoaPods version are you using, and what iOS versions are you targeting? We will try to repro this issue.

**Comment by ldiqual** [comment]
@john-gu Cocoapods 1.0.1 and iOS 9 only. Fyi we decided to go with another vendor so I won't be able to help investigating this issue anymore.

**Comment by pevasquez** [comment]
Hey, just wanted to bump this. I am having the same issue with iOS 9 + Cocoapods 1.0.1.
For some reason, Cocoapods doesn't seem to be adding MobileAppTracker.framework nor its dependencies (iAd, CoreServices, Telephony) to the linked binaries section of my library. Adding those manually works around the problem. I am still looking for a way to make this permanent. Please ping for anything you need on this!

**Comment by john-gu** [comment]
Ah I see the issue. It is most likely the `use_frameworks!` in your `Podfile`. Please try removing this line before running `pod install`.

Our library is currently built as a static library and cannot be used in conjunction with this option.

**Comment by pevasquez** [comment]
Huh, we specifically intend to work with use_frameworks! as we need to include external swift code. Guess we'll be wrapping the library in a framework ourselves then.
The thing is, we've managed to not get the 'static dependencies' error, but still the link-time dependencies are not included in the project.

**Comment by mattfeury** [comment]
another +1 to this issue. not being able to include the library via cocoapod will force us to find another product that facilitates easier development .

**Comment by kevmalek** [comment]
Still no resolution on this? We're on a Swift codebase using CocoaPods. This is a common setup that still isn't supported.

**Comment by mattfeury** [comment]
@kevmalek due to this bug, my co switched to appsflyer and have had a much better experience.

**Comment by john-gu** [comment]
We've updated this library to reference the TUNE 5.x iOS SDK which is a dynamic library: https://github.com/TuneOSS/segment-integration-ios/releases/tag/1.1.0 

Please try updating to the 1.1.0 pod to resolve this issue. Thanks!
